#\DeclareLyXModule{Duarte Theorems Unnumbered Propositions}
#\DeclareCategory{My Custom Modules}
#DescriptionBegin
#Unnumbered Propositions.
#DescriptionEnd
#Excludes: theorems-ams | theorems-starred | theorems-std
#Requires: duarte_theorems | duarte_theorems_sec_subsec

# Author: Duarte Maia

Format 60

Style Proposition*
	CopyStyle             Theorem
	DependsOn             Proposition
	Category              Reasoning*
	LatexName             prop*
	LabelCounter          ""
	LabelString           "Proposition."
    RefPrefix             def
	Preamble
        \theoremstyle{nonumberplain}
        \theorembodyfont{\upshape}
        \theoremheaderfont{\bfseries}
        \theoremseparator{.}
		\renewtheorem{prop*}{Proposition}
        \theoremstyle{plain}
        \theorembodyfont{\upshape}
        \theoremheaderfont{\bfseries}
        \theoremseparator{.}
        \theoremnumbering{arabic}
        \theoremsymbol{}
	EndPreamble
End
