#\DeclareLyXModule{Duarte Theorems}
#\DeclareCategory{My Custom Modules}
#DescriptionBegin
#My standard ntheorem theorems
#DescriptionEnd
#Excludes: theorems-ams | theorems-starred | theorems-std

# Author: Duarte Maia

Format 104

Preamble
\usepackage[amsmath,thmmarks]{ntheorem}
EndPreamble


OutlinerName thm "Definitions & Theorems"

Style Theorem
	Category              Reasoning
	Margin                First_Dynamic
	LatexType             Environment
	LatexName             thm
    RefPrefix             thm
	NextNoIndent          1
	ResetArgs             1
	AddToToc              thm
	IsTocCaption          1
	Argument 1
		LabelString    "Additional Theorem Text"
		Tooltip        "Additional text appended to the theorem header"
		IsTocCaption      1
	EndArgument
	LabelSep              xx
	ParIndent             MMM
	ParSkip               0.4
	ItemSep               0.2
	TopSep                0.7
	BottomSep             0.7
	ParSep                0.3
	Align                 Block
	AlignPossible         Left
	LabelType             Static
	LabelCounter          theorem
	LabelString           "Theorem \thetheorem."
	Font
	  Shape               Up
	  Size                Normal
	EndFont
	LabelFont
	  Shape               Up
	  Series              Bold
	EndFont
	Preamble
        \newref{thm}{refcmd={Theorem~\ref{#1}}}
        \theoremstyle{plain}
        \theorembodyfont{\upshape}
        \theoremheaderfont{\bfseries}
        \theoremseparator{.}
        \theoremnumbering{arabic}
        \theoremsymbol{}
        \newtheorem{thm}{Theorem}
	EndPreamble
	Requires              ntheorem
    Requires              refstyle
End

Style Proof
	CopyStyle             Theorem
	DependsOn             Theorem
	LatexName             proof
	LabelString           "Proof:"
    LabelCounter          ""
	AddToToc              ""
	Preamble
        \theoremstyle{nonumberplain}
        \theoremheaderfont{\itshape}
        \theorembodyfont{\upshape}
        \theoremseparator{:}
        \theoremsymbol{\ensuremath{\blacksquare}}
        \newtheorem{proof}{Proof}
        
        \theoremstyle{plain}
        \theorembodyfont{\upshape}
        \theoremheaderfont{\bfseries}
        \theoremseparator{.}
        \theoremnumbering{arabic}
        \theoremsymbol{}
	EndPreamble

	LabelFont
	  Shape               Italic
	  Series              Medium
	EndFont
    EndLabelType Filled_Box
    Requires amssymb
End

Style Definition
	CopyStyle             Theorem
	DependsOn             Theorem
	LatexName             definition
	LabelString           "Definition \thetheorem."
    RefPrefix             def
	Preamble
        \newref{def}{refcmd={Definition~\ref{#1}}}
		\newtheorem{definition}[thm]{Definition}
	EndPreamble
End

Style Proposition
	CopyStyle             Theorem
	DependsOn             Theorem
	LatexName             prop
	LabelString           "Proposition \thetheorem."
    RefPrefix             prop
	Preamble
        \newref{prop}{refcmd={Proposition~\ref{#1}}}
		\newtheorem{prop}[thm]{Proposition}
	EndPreamble
End

Style Lemma
	CopyStyle             Theorem
	DependsOn             Theorem
	LatexName             lemma
	LabelString           "Lemma \thetheorem."
    RefPrefix             lem
	Preamble
        \newref{lem}{refcmd={Lemma~\ref{#1}}}
		\newtheorem{lemma}[thm]{Lemma}
	EndPreamble
End

Style Remark
	CopyStyle             Theorem
	DependsOn             Theorem
	LatexName             remark
	LabelString           "Remark \thetheorem."
    RefPrefix             rmk
	Preamble
        \newref{rmk}{refcmd={Remark~\ref{#1}}}
		\newtheorem{remark}[thm]{Remark}
	EndPreamble
End

Style Corollary
	CopyStyle             Theorem
	DependsOn             Theorem
	LatexName             corollary
	LabelString           "Corollary \thetheorem."
    RefPrefix             cor
	Preamble
        \newref{cor}{refcmd={Corollary~\ref{#1}}}
		\newtheorem{corollary}[thm]{Corollary}
	EndPreamble
End

Style Example
	CopyStyle             Theorem
	DependsOn             Theorem
	LatexName             example
	LabelString           "Example \thetheorem."
    RefPrefix             ex
	Preamble
        \newref{ex}{refcmd={Example~\ref{#1}}}
		\newtheorem{example}[thm]{Example}
	EndPreamble
End


Style Claim
	CopyStyle             Theorem
	DependsOn             Theorem
	LatexName             claim
	LabelString           "Claim:"
    LabelCounter          ""
    RefPrefix             claim
	Preamble
        \theoremstyle{nonumberplain}
        \theorembodyfont{\upshape}
        \theoremseparator{:}
		\newtheorem{claim}[thm]{Claim}
        \theoremstyle{plain}
        \theorembodyfont{\upshape}
        \theoremheaderfont{\bfseries}
        \theoremseparator{.}
        \theoremnumbering{arabic}
        \theoremsymbol{}
	EndPreamble
End


Style Fact
	CopyStyle             Theorem
	DependsOn             Theorem
	LatexName             fact
	LabelString           "Fact \thetheorem."
    RefPrefix             fact
	Preamble
		\newtheorem{fact}[thm]{Fact}
	EndPreamble
End

Style Theorem*
	CopyStyle             Theorem
	DependsOn             Theorem
	Category              Reasoning*
	LatexName             thm*
	LabelCounter          ""
	LabelString           "Theorem."
	Preamble
        \theoremstyle{nonumberplain}
        \theorembodyfont{\upshape}
        \theoremheaderfont{\bfseries}
        \theoremseparator{.}
        \renewtheorem{thm*}{Theorem}
        \theoremstyle{plain}
        \theorembodyfont{\upshape}
        \theoremheaderfont{\bfseries}
        \theoremseparator{.}
        \theoremnumbering{arabic}
        \theoremsymbol{}
	EndPreamble
End

Style Corollary*
	CopyStyle             Theorem*
	DependsOn             Theorem*
	LatexName             corollary*
	LabelString           "Corollary."
	Preamble
        \theoremstyle{nonumberplain}
        \theorembodyfont{\upshape}
        \theoremheaderfont{\bfseries}
        \theoremseparator{.}
		\renewtheorem{corollary*}{Corollary}
        \theoremstyle{plain}
        \theorembodyfont{\upshape}
        \theoremheaderfont{\bfseries}
        \theoremseparator{.}
        \theoremnumbering{arabic}
        \theoremsymbol{}
	EndPreamble
End

Style Question*
	CopyStyle             Theorem*
	DependsOn             Theorem
	LatexName             question*
	LabelString           "Question."
	Preamble
        \theoremstyle{nonumberplain}
        \theorembodyfont{\upshape}
        \theoremheaderfont{\bfseries}
        \theoremseparator{.}
        \newtheorem{question*}{Question}
        \theoremstyle{plain}
        \theorembodyfont{\upshape}
        \theoremheaderfont{\bfseries}
        \theoremseparator{.}
        \theoremnumbering{arabic}
        \theoremsymbol{}
	EndPreamble
End

Style Conjecture
	CopyStyle             Theorem
	DependsOn             Theorem
	LatexName             conjecture
	LabelString           "Conjecture \thetheorem."
    RefPrefix             conj
	Preamble
        \newref{conj}{refcmd={Conjecture~\ref{#1}}}
		\newtheorem{conjecture}[thm]{Conjecture}
	EndPreamble
End



Counter theorem
	GuiName Theorem
	LaTeXName thm
	RefFormat thm "Theorem \arabic{theorem}"
	RefFormat lem "Lemma \arabic{theorem}"
	RefFormat prop "Proposition \arabic{theorem}"
	RefFormat fact "Fact \arabic{theorem}"
    RefFormat cor "Corollary \arabic{theorem}"
    RefFormat def "Definition \arabic{theorem}"
    RefFormat rmk "Remark \arabic{theorem}"
    RefFormat conj "Conjecture \arabic{theorem}"
    RefFormat ex "Example \arabic{theorem}"
End
