#\DeclareLyXModule{Duarte Theorems Unnumbered Definitions}
#\DeclareCategory{My Custom Modules}
#DescriptionBegin
#ntheorem theorems for exercises.
#DescriptionEnd
#Excludes: theorems-ams | theorems-starred | theorems-std
#Requires: duarte_theorems

# Author: Duarte Maia

Format 60

Style Definition*
	CopyStyle             Theorem
	DependsOn             Definition
	Category              Reasoning*
	LatexName             definition*
	LabelCounter          ""
	LabelString           "Definition."
    RefPrefix             def
	Preamble
        \theoremstyle{nonumberplain}
        \theorembodyfont{\upshape}
        \theoremheaderfont{\bfseries}
        \theoremseparator{.}
		\renewtheorem{definition*}{Definition}
        \theoremstyle{plain}
        \theorembodyfont{\upshape}
        \theoremheaderfont{\bfseries}
        \theoremseparator{.}
        \theoremnumbering{arabic}
        \theoremsymbol{}
	EndPreamble
End
